services:
  grafana:
    image: grafana/grafana:11.6.0
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=grafana-athena-datasource
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-us-east-1}
      - ACCOUNT_ID=${ACCOUNT_ID}
    volumes:
      - ./provisioning:/etc/grafana/provisioning
      - grafana-data-module7:/var/lib/grafana

volumes:
  grafana-data-module7:
