---
Metadata:
  AWSToolsMetrics:
    IaC_Generator: "arn:aws:cloudformation:us-east-1:879548554867:generatedTemplate/abcb625a-3757-4ddf-bf8c-0d534da6175d"
Resources:
  GlueDatabaseMyTestdb:
    UpdateReplacePolicy: "Retain"
    Type: "AWS::Glue::Database"
    DeletionPolicy: "Retain"
    Properties:
      DatabaseName: "my_test_db"
      CatalogId: "879548554867"
      DatabaseInput:
        CreateTableDefaultPermissions:
        - Permissions:
          - "ALL"
          Principal:
            DataLakePrincipalIdentifier: "IAM_ALLOWED_PRINCIPALS"
        Parameters: {}
        Name: "my_test_db"
  IAMRoleMyTestgluerole:
    UpdateReplacePolicy: "Retain"
    Type: "AWS::IAM::Role"
    DeletionPolicy: "Retain"
    Properties:
      Path: "/"
      ManagedPolicyArns:
      - "arn:aws:iam::879548554867:policy/my-test-glue-rolePolicy"
      - "arn:aws:iam::aws:policy/AWSGlueConsoleFullAccess"
      - "arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole"
      MaxSessionDuration: 3600
      RoleName: "my-test-glue-role"
      Description: ""
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Condition:
            StringEquals:
              aws:SourceAccount: "879548554867"
          Action: "sts:AssumeRole"
          Effect: "Allow"
          Principal:
            Service: "glue.amazonaws.com"
  GlueJobMyTestpyshelljob:
    UpdateReplacePolicy: "Retain"
    Type: "AWS::Glue::Job"
    DeletionPolicy: "Retain"
    Properties:
      MaxRetries: 0
      JobMode: "SCRIPT"
      Description: ""
      Timeout: 2880
      AllocatedCapacity: 0
      JobRunQueuingEnabled: false
      Name: "my_test_py_shell_job"
      Role: "arn:aws:iam::879548554867:role/my-test-glue-role"
      DefaultArguments:
        "--enable-job-insights": "false"
        "--job-language": "python"
        "--TempDir": "s3://my-test-bucket/temporary/"
        "--enable-observability-metrics": "false"
        "--enable-glue-datacatalog": "true"
        library-set: "analytics"
      ExecutionClass: "STANDARD"
      Command:
        ScriptLocation: "s3://my-test-bucket/scripts/py_shell_job.py"
        PythonVersion: "3.9"
        Name: "pythonshell"
      GlueVersion: "3.0"
      ExecutionProperty:
        MaxConcurrentRuns: 1
      MaxCapacity: 0.0625
  S3BucketMyTestathena:
    UpdateReplacePolicy: "Retain"
    Type: "AWS::S3::Bucket"
    DeletionPolicy: "Retain"
    Properties:
      AbacStatus: "Disabled"
      PublicAccessBlockConfiguration:
        RestrictPublicBuckets: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        BlockPublicAcls: true
      BucketName: "my-test-athena"
      OwnershipControls:
        Rules:
        - ObjectOwnership: "BucketOwnerEnforced"
      BucketEncryption:
        ServerSideEncryptionConfiguration:
        - BucketKeyEnabled: true
          BlockedEncryptionTypes:
            EncryptionType:
            - "SSE-C"
          ServerSideEncryptionByDefault:
            SSEAlgorithm: "AES256"
  S3BucketMyTest:
    UpdateReplacePolicy: "Retain"
    Type: "AWS::S3::Bucket"
    DeletionPolicy: "Retain"
    Properties:
      AbacStatus: "Disabled"
      PublicAccessBlockConfiguration:
        RestrictPublicBuckets: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        BlockPublicAcls: true
      BucketName: "my-test-bucket"
      OwnershipControls:
        Rules:
        - ObjectOwnership: "BucketOwnerEnforced"
      BucketEncryption:
        ServerSideEncryptionConfiguration:
        - BucketKeyEnabled: true
          BlockedEncryptionTypes:
            EncryptionType:
            - "SSE-C"
          ServerSideEncryptionByDefault:
            SSEAlgorithm: "AES256"
  IAMManagedPolicyPolicymytestgluerolePolicy:
    UpdateReplacePolicy: "Retain"
    Type: "AWS::IAM::ManagedPolicy"
    DeletionPolicy: "Retain"
    Properties:
      ManagedPolicyName: "my-test-glue-rolePolicy"
      Path: "/"
      Description: ""
      Groups: []
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Condition:
            StringEquals:
              aws:ResourceAccount: "879548554867"
          Resource:
          - "arn:aws:s3:::my-test-bucket/*"
          Action:
          - "s3:GetObject"
          - "s3:PutObject"
          Effect: "Allow"
      Roles:
      - "my-test-glue-role"
      Users: []
